In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

np.int64(8)

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[0:6]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_arr[:] = 99

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_copy = arr.copy()

In [18]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy[:] = 200

In [20]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
# mat[row, column]
# mat[row][col]

In [23]:
mat = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [24]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
mat[0]

array([ 5, 10, 15])

In [26]:
mat[2]

array([35, 40, 45])

In [27]:
mat[1][1]

np.int64(25)

In [28]:
mat[1,1]

np.int64(25)

In [29]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
mat[0,2]

np.int64(15)

In [31]:
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [32]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
mat[1:,0:2]

array([[20, 25],
       [35, 40]])

In [34]:
# Conditional Selection

In [35]:
arr = np.arange(1,11)

In [36]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [38]:
bool_arr = arr > 4

In [39]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [41]:
arr[arr <= 9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])