In [2]:
import numpy as np

In [5]:
# Creating Numpy Array

In [6]:
my_list = [1, 2, 3]

In [8]:
x = np.array(my_list)

In [9]:
type(x)

numpy.ndarray

In [10]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [14]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [3]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
type(1.0)

float

In [6]:
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.linspace(0, 10, 51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5, 4)

array([[0.29359689, 0.55569817, 0.97278392, 0.8850482 ],
       [0.87109818, 0.5682519 , 0.58691472, 0.45572428],
       [0.91665495, 0.70832857, 0.58363397, 0.79733246],
       [0.09388806, 0.76891928, 0.83595826, 0.20798886],
       [0.66081603, 0.29863523, 0.01975194, 0.54374419]])

In [19]:
np.random.randn(5)

array([-0.74564738, -0.19434103,  0.22169051,  0.7872831 ,  0.8725791 ])

In [20]:
np.random.randn(5,4)

array([[-0.95228412, -0.14822759, -0.39194772,  0.10211627],
       [ 0.95175202, -0.65390253,  0.51801929, -0.41174739],
       [-0.50322043, -0.46221983, -1.23147924, -0.77645563],
       [-0.32297828, -0.32631246, -0.83799195,  1.03815193],
       [ 2.63104171,  1.22335606, -0.78996318, -0.56565188]])

In [24]:
np.random.randint(1,100, 10)

array([51, 37, 66, 36, 19, 62, 85, 40, 47, 44], dtype=int32)

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([ 5, 49, 25,  5, 19, 12, 16, 48, 49, 44], dtype=int32)

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr.reshape(25,1).shape

(25, 1)

In [33]:
arr.dtype

dtype('int64')

In [34]:
ranarr

array([ 5, 49, 25,  5, 19, 12, 16, 48, 49, 44], dtype=int32)

In [35]:
ranarr.max()

np.int32(49)

In [36]:
ranarr.argmax()

np.int64(1)